// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUsBcuwBRzLVp-9rj2QWFelg8kS4AqoN8',
    appId: '1:259201710740:web:b289ec4cc06b287b701281',
    messagingSenderId: '259201710740',
    projectId: 'sohn-webapp',
    authDomain: 'sohn-webapp.firebaseapp.com',
    storageBucket: 'sohn-webapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYJNzDyVqonUgQcxq3lX27RU-Uj9kdwc',
    appId: '1:259201710740:android:255f0b1a3b955c4a701281',
    messagingSenderId: '259201710740',
    projectId: 'sohn-webapp',
    storageBucket: 'sohn-webapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdo7C2I2SnmOV9LSTU9P1gjf3yjEspWUE',
    appId: '1:259201710740:ios:76861be7e74baa46701281',
    messagingSenderId: '259201710740',
    projectId: 'sohn-webapp',
    storageBucket: 'sohn-webapp.appspot.com',
    iosClientId: '259201710740-teai7ratovdevc9trlenaln97lel06sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdo7C2I2SnmOV9LSTU9P1gjf3yjEspWUE',
    appId: '1:259201710740:ios:76861be7e74baa46701281',
    messagingSenderId: '259201710740',
    projectId: 'sohn-webapp',
    storageBucket: 'sohn-webapp.appspot.com',
    iosClientId: '259201710740-teai7ratovdevc9trlenaln97lel06sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );
}
